AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-wiki

  Sample SAM Template for sam-wiki

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SamWikiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sam-wiki/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        SamWiki:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wiki
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SamWikiApi:
    Description: "API Gateway endpoint URL for Prod stage for Sam Wiki function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/wiki/"
  SamWikiFunction:
    Description: "Sam Wiki Lambda Function ARN"
    Value: !GetAtt SamWikiFunction.Arn
  SamWikiFunctionIamRole:
    Description: "Implicit IAM Role created for Sam Wiki function"
    Value: !GetAtt SamWikiFunctionRole.Arn
